# Generated by Django 3.2.5 on 2022-04-18 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('title', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('category', models.TextField(null=True)),
                ('link', models.TextField()),
                ('date', models.TextField(null=True)),
                ('source', models.URLField(null=True)),
                ('img', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
