# Generated by Django 3.2.5 on 2022-04-16 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='headline',
            old_name='image',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='headline',
            old_name='url',
            new_name='link',
        ),
        migrations.RemoveField(
            model_name='headline',
            name='id',
        ),
        migrations.AddField(
            model_name='headline',
            name='date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='headline',
            name='source',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='headline',
            name='title',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
