# Generated by Django 3.2.5 on 2022-04-16 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20220416_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headline',
            name='date',
            field=models.TextField(default=None),
        ),
    ]
